build-llvm.py: Avoid crash in clang_version with Python 3.5
Traceback (most recent call last):
  File "./build-llvm.py", line 436, in <module>
    main()
  File "./build-llvm.py", line 419, in main
    env_vars = EnvVars(*check_cc_ld_variables(root_folder))
  File "./build-llvm.py", line 210, in check_cc_ld_variables
    if clang_version(cc, root_folder) < 30900:
  File "./build-llvm.py", line 36, in clang_version
    return int(subprocess.check_output(command).decode())
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1205, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.5/os.py", line 862, in fsencode
    raise TypeError("expect bytes or str, not %s" % type(filename).__name__)
TypeError: expect bytes or str, not PosixPath

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>