kernel: Bump to Linux 5.5.9
Stable 5.5.9 includes a fix [1] for the following error, which breaks
PGO builds targeting x86 on newer LLVM revisions:

ld.lld: error: duplicate symbol: __force_order
>>> defined at kaslr_64.c
>>>            arch/x86/boot/compressed/kaslr_64.o:(__force_order)
>>> defined at pgtable_64.c
>>>            arch/x86/boot/compressed/pgtable_64.o:(.bss+0x2000)

[1] https://lore.kernel.org/lkml/20200310123644.028693381@linuxfoundation.org/raw

Signed-off-by: Danny Lin <danny@kdrag0n.dev>