tc_build: binutils: Discard .sframe sections
When building binutils using a version of binutils 2.46 (which has
SFrame v3 support) against a version of glibc with '--enable-sframe'
(such as Arch Linux's before [1]), there may be an error:

  libiberty/atexit.c: In function ‘atexit’:
  libiberty/atexit.c:23:3: error: implicit declaration of function ‘on_exit’ [-Wimplicit-function-declaration]
     23 |   on_exit (f, 0);
        |   ^~~~~~~
  make[2]: *** [Makefile:593: atexit.o] Error 1

which ultimately comes from a failure in configure:

  configure:7219: checking for atexit
  configure:7219: gcc -o conftest -O2        conftest.c  >&5
  .../binutils/2.46.50-2026-01-29_21-13-50-be3c73b4610a7ccf915daca693565bc895f3584e/bin/ld: input SFrame sections with different format versions prevent .sframe generation
  .../binutils/2.46.50-2026-01-29_21-13-50-be3c73b4610a7ccf915daca693565bc895f3584e/bin/ld: final link failed
  collect2: error: ld returned 1 exit status

If the linker has the '--discard-sframe' option, use it to avoid these
errors, which could happen in the future if SFrame v4 comes about.

Link: https://gitlab.archlinux.org/archlinux/packaging/packages/glibc/-/commit/8b658c9ebee21c44138ac7e237b50100648e5c00 [1]
Signed-off-by: Nathan Chancellor <nathan@kernel.org>